// Placeholder model file
// This file will be auto-generated by convert_to_tflite.py
// After training your model, run: python convert_to_tflite.py
// Then replace this file with the generated model_data.h

#ifndef MODEL_DATA_H
#define MODEL_DATA_H

// This is a placeholder - the actual model will be generated after training
const unsigned int model_len = 0;
const unsigned char model_data[] = {};

#endif  // MODEL_DATA_H
